import turtle
def draw_letters():
    window = turtle.Screen()
    window.bgcolor("red")
    brad = turtle.Turtle()
    brad.shape("turtle")
    brad.color("yellow")
    brad.speed(2)
    brad.goto(0,0)
    brad.right(180)
    brad.forward(100)
    brad.left(90)
    brad.forward(100)
    brad.left(90)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.penup()
    brad.goto(150,0)
    brad.pendown()
    brad.left(90)
    brad.forward(200)
    brad.left(90)
    brad.circle(100,180)
    window.exitonclick()
draw_letters()
